# Generated by Django 3.1.4 on 2020-12-15 18:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_default_date', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=utc))),
                ('monetary_decimal_places', models.PositiveIntegerField(default=6)),
                ('db_date_format', models.CharField(default='%Y-%m-%d %H:%M:%S', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
