# Generated by Django 3.1.5 on 2021-01-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashmanagementsettings',
            name='client_one_deposit_max',
        ),
        migrations.RemoveField(
            model_name='cashmanagementsettings',
            name='client_one_deposit_min',
        ),
        migrations.RemoveField(
            model_name='cashmanagementsettings',
            name='client_withdrawal_max',
        ),
        migrations.RemoveField(
            model_name='cashmanagementsettings',
            name='client_withdrawal_time_period',
        ),
        migrations.AddField(
            model_name='cashmanagementsettings',
            name='client_external_withdrawal_max',
            field=models.DecimalField(decimal_places=6, default=10000, help_text='Maximum amount in USD that a client can freely withdraw from a portfolio to an external source', max_digits=18),
        ),
        migrations.AddField(
            model_name='cashmanagementsettings',
            name='client_external_withdrawal_time_period',
            field=models.DecimalField(decimal_places=6, default=1, help_text="Time period in days (24 hour days) over which to calculate the total amount  of withdrawals from a client's portfolio to an external source. The idea is that a client cannot freely withdraw more than the client_external_withdrawal_maximum within this time period without triggering a review by a broker.", max_digits=18),
        ),
        migrations.AddField(
            model_name='cashmanagementsettings',
            name='client_one_external_deposit_max',
            field=models.DecimalField(decimal_places=6, default=10000, help_text='Maximum amount in USD that a client can deposit into a portfolio at one time from an external source.', max_digits=18),
        ),
        migrations.AddField(
            model_name='cashmanagementsettings',
            name='client_one_external_deposit_min',
            field=models.DecimalField(decimal_places=6, default=100, help_text='Minimum amount in USD that a client can deposit into a portfolio at one time from an external source', max_digits=18),
        ),
    ]
