# Generated by Django 3.1.4 on 2020-12-17 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_stockmanagementsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmanagementsettings',
            name='internal_short_share_threshold',
            field=models.IntegerField(default=1000, help_text='The maximum allowable share deficit.'),
        ),
    ]
