# Generated by Django 3.1.5 on 2021-01-21 02:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='A nickname for this portfolio', max_length=255)),
                ('open_date', models.DateTimeField(auto_now_add=True)),
                ('close_date', models.DateTimeField(blank=True, default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=utc))),
                ('cash', models.DecimalField(decimal_places=6, default=0, help_text='The amount of cash in USD held in this portfolio.', max_digits=20)),
                ('description', models.CharField(default='', help_text='A brief description of this portfolio.', max_length=1000)),
                ('portfolio_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockTransactRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_abbr', models.CharField(blank=True, default='', max_length=50)),
                ('ticker', models.CharField(blank=True, default='', max_length=50)),
                ('order_type', models.CharField(blank=True, choices=[('buy', 'Stock buy order.'), ('sell', 'Stock sell order.')], default='buy', max_length=50)),
                ('order_placement_datetime', models.DateTimeField(blank=True, default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=utc), help_text='The datetime in UTC the order was placed.')),
                ('order_execution_datetime', models.DateTimeField(blank=True, default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=utc), help_text='The datetime in UTC the order was executed')),
                ('price', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=50)),
                ('quantity', models.PositiveIntegerField(blank=True, default=0)),
                ('order_status', models.CharField(blank=True, choices=[('approved', 'Order passes automatic checks.'), ('rejected', 'Order cannot be processed.'), ('processing', 'Order is currently processing.'), ('under_review', 'Order is currently under review.'), ('completed', 'Order has been completed')], default='processing', max_length=50)),
                ('order_class', models.CharField(blank=True, choices=[('internal', 'This is an internal order.'), ('external', 'This is an external order.'), ('split', 'This order has been split into an external order and an internal order.'), ('undetermined', 'The class of this order has not yet been determined.')], default='undetermined', max_length=50)),
                ('broker_review_requested', models.BooleanField(default=False, help_text='Indicates whether or not the user has requested this order to be manually reviewed by a broker.')),
                ('message', models.CharField(blank=True, default='', max_length=1200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('order_id', models.CharField(blank=True, default='', max_length=50)),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('order_part_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='table.stocktransactrecord')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocktransactions', to='table.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_abbr', models.CharField(default='', max_length=100)),
                ('exchange_long', models.CharField(default='', max_length=100)),
                ('ticker', models.CharField(default='', max_length=100)),
                ('name', models.CharField(default='', max_length=200)),
                ('summary', models.CharField(default='', max_length=1000)),
                ('price', models.DecimalField(decimal_places=6, default=0, max_digits=50)),
                ('logo', models.CharField(default='', max_length=1000)),
                ('date', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=utc))),
            ],
            options={
                'unique_together': {('ticker', 'date')},
            },
        ),
        migrations.CreateModel(
            name='CashTransactionRecord',
            fields=[
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, choices=[('approved', 'Order passes automatic checks.'), ('rejected', 'Order cannot be processed.'), ('processing', 'Order is currently processing.'), ('under_review', 'Order is currently under review.'), ('completed', 'Order has been completed')], default='processing', max_length=50)),
                ('currency_type', models.CharField(blank=True, choices=[('USD', 'United States Dollar'), ('EUR', 'European Euro'), ('GBP', 'British Pound'), ('JPY', 'Japanese Yen'), ('CAD', 'Canadian Dollar'), ('CHF', 'Swiss Franc')], default='USD', max_length=10)),
                ('amount', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=50)),
                ('amount_in_USD', models.DecimalField(blank=True, decimal_places=6, default=0, help_text='amount of currency converted to USD', max_digits=50)),
                ('transaction_type', models.CharField(blank=True, choices=[('deposit', 'Cash deposit in to the associated Portfolio.'), ('withdrawal', 'Cash withdrawal from the associated Portfolio.')], default='deposit', max_length=20)),
                ('transaction_to', models.CharField(blank=True, default='', help_text='The account number to which the transaction is directed.', max_length=50)),
                ('transaction_from', models.CharField(blank=True, default='', help_text='The account number from which the transaction is directed.', max_length=50)),
                ('transaction_fail_message', models.CharField(blank=True, default='', help_text='A short message describing why the transaction has failed. 0 if no failure.', max_length=50)),
                ('transaction_datetime', models.DateTimeField(blank=True, default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=utc))),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashtransactions', to='table.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='StockInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_abbr', models.CharField(blank=True, default='', max_length=50)),
                ('ticker', models.CharField(blank=True, default='', max_length=50)),
                ('quantity', models.PositiveIntegerField(blank=True, default=0)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockinventory', to='table.portfolio')),
            ],
            options={
                'unique_together': {('portfolio', 'ticker')},
            },
        ),
    ]
