# Generated by Django 3.1.4 on 2020-12-08 18:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('percent_change', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('open_date', models.DateTimeField(auto_now_add=True)),
                ('close_date', models.DateTimeField(blank=True, default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=utc))),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_abbr', models.CharField(default='', max_length=100)),
                ('exchange_long', models.CharField(default='', max_length=100)),
                ('ticker', models.CharField(default='', max_length=100)),
                ('name', models.CharField(default='', max_length=200)),
                ('summary', models.CharField(default='', max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('logo', models.CharField(default='', max_length=1000)),
                ('date_retrieved', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='StockTransactRecord',
            fields=[
                ('exchange_abbr', models.CharField(blank=True, default='', max_length=50)),
                ('ticker', models.CharField(blank=True, default='', max_length=50)),
                ('buy_date', models.DateTimeField(blank=True, default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=utc))),
                ('sell_date', models.DateTimeField(blank=True, default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=utc))),
                ('buy_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=50)),
                ('sell_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=50)),
                ('quantity', models.PositiveIntegerField(blank=True, default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocktransactions', to='table.portfolio')),
            ],
        ),
    ]
