# Generated by Django 3.1.4 on 2020-12-08 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
