# Generated by Django 3.1.5 on 2021-01-21 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashtransactionrecord',
            name='transaction_fail_message',
        ),
        migrations.AddField(
            model_name='cashtransactionrecord',
            name='transaction_conditions',
            field=models.CharField(blank=True, default='', help_text='A json text file giving the conditions at time of failure. 0 if no failure.', max_length=1000),
        ),
    ]
