# Generated by Django 3.1.5 on 2021-01-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_auto_20210121_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashtransactionrecord',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('external_deposit', 'Cash deposit in to the associated Portfolio from external source.'), ('external_withdrawal', 'Cash withdrawal from the associated Portfolio to external source.'), ('internal_stock_buy_cover', 'Cash withdrawal from associated portfolio to cover the purchase of stock through this company.'), ('stock_sell_proceeds', 'Cash deposit into the associated portfolio from the sale of stock through this company.')], default='external_withdrawal', max_length=50),
        ),
    ]
