# Generated by Django 3.1.4 on 2020-12-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0003_auto_20201209_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stocktransactrecord',
            old_name='buy_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='stocktransactrecord',
            old_name='buy_quantity',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='stocktransactrecord',
            old_name='buy_date',
            new_name='transaction_date',
        ),
        migrations.RemoveField(
            model_name='stocktransactrecord',
            name='sell_date',
        ),
        migrations.RemoveField(
            model_name='stocktransactrecord',
            name='sell_price',
        ),
        migrations.RemoveField(
            model_name='stocktransactrecord',
            name='sell_quantity',
        ),
        migrations.AddField(
            model_name='stocktransactrecord',
            name='transaction_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
