# Generated by Django 3.1.4 on 2020-12-12 15:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0006_auto_20201210_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constants',
            fields=[
                ('id', models.CharField(default='CONSTANT', max_length=30, primary_key=True, serialize=False)),
                ('value', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='stocktransactrecord',
            old_name='transaction_date',
            new_name='order_execution_datetime',
        ),
        migrations.RenameField(
            model_name='stocktransactrecord',
            old_name='transaction_type',
            new_name='order_type',
        ),
        migrations.AddField(
            model_name='stocktransactrecord',
            name='order_placement_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=utc)),
        ),
    ]
