# Generated by Django 3.1.4 on 2020-12-14 18:48

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0007_auto_20201212_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashTransactionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency_type', models.CharField(blank=True, default='USD', max_length=10)),
                ('amount', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=50)),
                ('transaction_type', models.CharField(blank=True, default='', max_length=20)),
                ('transaction_to', models.CharField(blank=True, default='', max_length=50)),
                ('transaction_from', models.CharField(blank=True, default='', max_length=50)),
                ('transaction_datetime', models.DateTimeField(blank=True, default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=utc))),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashtransactions', to='table.portfolio')),
            ],
        ),
    ]
