# Generated by Django 3.1.4 on 2020-12-14 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('table', '0009_auto_20201214_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransactrecord',
            name='order_type',
            field=models.CharField(blank=True, choices=[('buy', 'Stock buy order.'), ('sell', 'Stock sell order.')], default='buy', max_length=100),
        ),
        migrations.CreateModel(
            name='StockInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_abbr', models.CharField(blank=True, default='', max_length=50)),
                ('ticker', models.CharField(blank=True, default='', max_length=50)),
                ('quantity', models.PositiveIntegerField(blank=True, default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
