# Generated by Django 3.1.4 on 2020-12-14 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0010_auto_20201214_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinventory',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.portfolio'),
        ),
    ]
