# Generated by Django 3.1.4 on 2020-12-15 16:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('table', '0011_auto_20201214_2207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockinventory',
            old_name='owner',
            new_name='portfolio',
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='StockOrderRequestRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_abbr', models.CharField(blank=True, default='', max_length=50)),
                ('ticker', models.CharField(blank=True, default='', max_length=50)),
                ('order_type', models.CharField(blank=True, choices=[('buy', 'Stock buy order.'), ('sell', 'Stock sell order.')], default='buy', max_length=100)),
                ('price', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=50)),
                ('quantity', models.PositiveIntegerField(blank=True, default=0)),
                ('request_datetime', models.DateTimeField(blank=True, default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=utc))),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockorderrequests', to='table.portfolio')),
            ],
        ),
    ]
