# Generated by Django 3.1.4 on 2020-12-15 20:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0012_auto_20201215_1636'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Constants',
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='cash',
            field=models.DecimalField(decimal_places=6, default=0, help_text='The amount of cash in USD held in this portfolio.', max_digits=20),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='description',
            field=models.CharField(default='', help_text='A brief description of this portfolio.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='name',
            field=models.CharField(default='', help_text='A nickname for this portfolio', max_length=255),
        ),
        migrations.AlterField(
            model_name='stockorderrequestrecord',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
