# Generated by Django 3.1.4 on 2020-12-16 19:24

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0014_auto_20201215_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransactrecord',
            name='broker_review_requested',
            field=models.BooleanField(default=False, help_text='Indicates whether or not the user has requested this order to be manually reviewed by a broker.'),
        ),
        migrations.AddField(
            model_name='stocktransactrecord',
            name='message',
            field=models.CharField(blank=True, default='', max_length=1200),
        ),
        migrations.AddField(
            model_name='stocktransactrecord',
            name='order_class',
            field=models.CharField(blank=True, choices=[('internal', 'This is an internal order.'), ('external', 'This is an external order.')], default='external', max_length=50),
        ),
        migrations.AddField(
            model_name='stocktransactrecord',
            name='order_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='stocktransactrecord',
            name='order_status',
            field=models.CharField(blank=True, choices=[('approved', 'Order passes automatic checks.'), ('rejected', 'Order fails automatic checks.'), ('processing', 'Order is currently processing.'), ('under_review', 'Order is currently under review.')], default='processing', max_length=50),
        ),
        migrations.AlterField(
            model_name='stockinventory',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockinventory', to='table.portfolio'),
        ),
        migrations.AlterField(
            model_name='stocktransactrecord',
            name='order_execution_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=utc), help_text='The datetime in UTC the order was executed'),
        ),
        migrations.AlterField(
            model_name='stocktransactrecord',
            name='order_placement_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=utc), help_text='The datetime in UTC the order was placed.'),
        ),
        migrations.AlterField(
            model_name='stocktransactrecord',
            name='order_type',
            field=models.CharField(blank=True, choices=[('buy', 'Stock buy order.'), ('sell', 'Stock sell order.')], default='buy', max_length=50),
        ),
        migrations.DeleteModel(
            name='StockOrderRequestRecord',
        ),
    ]
