# Generated by Django 3.1.4 on 2020-12-16 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0015_auto_20201216_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransactrecord',
            name='order_part_of',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='table.stocktransactrecord'),
        ),
        migrations.AlterField(
            model_name='stocktransactrecord',
            name='order_class',
            field=models.CharField(blank=True, choices=[('internal', 'This is an internal order.'), ('external', 'This is an external order.'), ('split', 'This order has been split into an external order and an internal order.'), ('undetermined', 'The class of this order has not yet been determined.')], default='undetermined', max_length=50),
        ),
    ]
