# Generated by Django 3.1.4 on 2020-12-16 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0016_auto_20201216_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransactrecord',
            name='order_part_of',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='table.stocktransactrecord'),
        ),
    ]
