# Generated by Django 3.1.4 on 2020-12-16 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0018_auto_20201216_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransactrecord',
            name='order_status',
            field=models.CharField(blank=True, choices=[('approved', 'Order passes automatic checks.'), ('rejected', 'Order cannot be processed.'), ('processing', 'Order is currently processing.'), ('under_review', 'Order is currently under review.')], default='processing', max_length=50),
        ),
    ]
